In [5]:
import numpy as np

In [142]:
#random arrays
ar_two = np.random.randint(20,50, size = (5,4))#two dimensional array
ar_two

array([[43, 49, 41, 45],
       [29, 21, 34, 35],
       [42, 45, 40, 27],
       [45, 23, 29, 43],
       [29, 45, 47, 29]])

In [84]:
np.random.rand(2,5)

array([[0.94011415, 0.7933182 , 0.173469  , 0.22467237, 0.64654105],
       [0.96140025, 0.433876  , 0.5055879 , 0.55711823, 0.6624907 ]])

In [92]:
print(np.random.randn(100).mean())

0.1750650677281289


In [95]:
np.zeros((4,16))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [109]:
#identity
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [115]:
#arange
arr = np.arange(1,40,2).reshape(5,4)
arr

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39]])

In [126]:
#one value
np.full((3,4),8,dtype="float")

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [144]:
ar_two

array([[43, 49, 41, 45],
       [29, 21, 34, 35],
       [42, 45, 40, 27],
       [45, 23, 29, 43],
       [29, 45, 47, 29]])

In [143]:
ar_two.ravel(order = "f")

array([43, 29, 42, 45, 29, 49, 21, 45, 23, 45, 41, 34, 40, 29, 47, 45, 35,
       27, 43, 29])

In [139]:
ar_two.shape

4

In [145]:
ar_two.size

20

In [148]:
ar_two.reshape(-1,4)

array([[43, 49, 41, 45],
       [29, 21, 34, 35],
       [42, 45, 40, 27],
       [45, 23, 29, 43],
       [29, 45, 47, 29]])

In [11]:
a = np.random.randint(5, size = (4,5))
np.vsplit(a,2)

[array([[0, 3, 1, 3, 3],
        [1, 0, 3, 2, 1]]),
 array([[3, 3, 2, 4, 3],
        [1, 1, 3, 4, 3]])]